### ISSUE TITLE
No MediaQuery widget found error

### ISSUE THREAD

**Issue by luis-cruzt** [CaiJingLong/flutter_load_widget#13]
Hi, i'm using the example code provided in your package, but when i add a textformfield and double tap it the error:
No MediaQuery widget found error appears.

Also, i've been searching and this is what i found:
https://stackoverflow.com/questions/62178788/flutter-easyloading-library-no-mediaquery-widget-found-error

That works with that library, but how to fix with yours?

**Comment by CaiJingLong** [comment]
Use next code to include the library.

```dart
MaterialApp(
  builder: (context, widget) {
    return LoadingProvider(
      child: widget,
    );
  },
);
```

**Comment by luis-cruzt** [comment]
Didn't work :(

**Comment by vytautas-pranskunas-** [comment]
Worked for me

**Comment by harimayco** [comment]
> Use next code to include the library.
> 
> ```dart
> MaterialApp(
>   builder: (context, widget) {
>     return LoadingProvider(
>       child: widget,
>     );
>   },
> );
> ```

worked for me, Thanks mate!

**Comment by luis-cruzt** [comment]
Well, it doesn't work if you wrap your application like this:
`
LoadingProvider(
  child: MaterialApp(),
);
`

Using the following code works:
`
void main() {
  runApp(
    LoadingProvider(
      child: MyApp(),
    ),
  );
}
`

I was using the widget MultiProvider maybe that was interfering with this widget.

I'll close this issue now as it seems that no one has this issue now.

**Comment by gabsf-dev** [comment]
@luis-cruzt i'm having the same issue using the MultiProvider, any update in user? Another lib that makes the same as this?

**Comment by luis-cruzt** [comment]
@GabrielF9 no sorry, i opted to use this [package](https://pub.dev/packages/loader_overlay) and is working fine in my app.

**Comment by gabsf-dev** [comment]
@luis-cruzt man, thanks so much, me and my job friends sends the best love you to you hahaha!! Saved the deploy friday
