### ISSUE TITLE
Not showing while hiding soft keyboard

### ISSUE THREAD

**Issue by meeftah** [CaiJingLong/flutter_load_widget#14]
I want to hide soft keyboard when login button clicked with
`// FocusScope.of(context).requestFocus();`

showLoadingDialog() follow after that, but it didn't show....unless I clicked the login button again (after soft keyboard is hidden)

any thoughts?

**Comment by bardez** [comment]
Same problem here!

**Comment by ephraimilunga** [comment]
For anyone having this issue, I've managed to implement a hack as follow: 

```
FocusScope.of(context).unfocus(); // hide the keyboard

await Future.delayed(Duration(milliseconds: 550)); // wait for few milliseconds

await showLoadingDialog(tapDismiss: false); // then show the loader

// re-show the keyboard for any reason. eg. if an error occurs.
FocusScope.of(context).requestFocus(); 
```

@meeftah  @bardez FYI
