### ISSUE TITLE
 App crash when double click or long press on textfield on flutter version 1.17.0

### ISSUE THREAD

**Issue by linhle1412** [CaiJingLong/flutter_load_widget#15]
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building
flutter: _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#f3d38](dirty, state:
flutter: _OverlayEntryWidgetState#b698c):
flutter: No MediaQuery widget found.
flutter: _OverlayEntryWidget widgets require a MediaQuery widget ancestor.
flutter: The specific widget that could not find a MediaQuery ancestor was:
flutter:   _OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#f3d38]
flutter: The ownership chain for the affected widget is:
flutter:   "_OverlayEntryWidget-[LabeledGlobalKey<_OverlayEntryWidgetState>#f3d38] ← _Theatre ←
flutter:   Overlay-[LabeledGlobalKey<OverlayState>#bb320] ← Directionality ←
flutter:   LoadingProvider-[LabeledGlobalKey<_LoadingProviderState>#8efe7] ← [root]"
flutter: Typically, the MediaQuery widget is introduced by the MaterialApp or WidgetsApp widget at the top of
flutter: your application widget tree.
flutter:
flutter: The relevant error-causing widget was:
flutter:   Overlay-[LabeledGlobalKey<OverlayState>#bb320]
flutter:   file:///Users/kaitou/.pub-cache/hosted/pub.dartlang.org/load-0.1.6/lib/src/provider.dart:51:14
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      debugCheckHasMediaQuery.<anonymous closure> (package:flutter/src/widgets/debug.dart:215:7)
flutter: #1      debugCheckHasMediaQuery (package:flutter/src/widgets/debug.dart:227:4)
flutter: #2      _CupertinoTextSelectionControls.buildToolbar (package:flutter/src/cupertino/text_selection.dart:308:12)
flutter: #3      TextSelectionOverlay._buildToolbar (package:flutter/src/widgets/text_selection.dart:556:34)
flutter: #4      _OverlayEntryWidgetState.build (package:flutter/src/widgets/overlay.dart:177:34)
flutter: #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:4619:28)
flutter: #6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4502:15)
flutter: #7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4481:5)
flutter: #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4666:11)
flutter: #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
flutter: #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
flutter: #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
flutter: #14     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5580:32)
flutter: #15     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:5957:17)
flutter: #16     Element.updateChild (package:flutter/src/widgets/framework.dart:3201:15)
flutter: #17     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4527:16)
flutter: #18     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4675:11)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
flutter: #20     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
flutter: #21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:20)
flutter: #22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
flutter: #23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
flutter: #24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
flutter: #25     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:968:5)
flutter: #29     _invoke (dart:ui/hooks.dart:261:10)
flutter: #30     _drawFrame (dart:ui/hooks.dart:219:3)

**Comment by linhle1412** [comment]
This error appears in flutter version 1.17.0, and fix by wrap LoadingProvider to MaterialApp builder
`MaterialApp(
  builder: (context, widget) {
    return LoadingProvider(
      child: widget,
    );
  },
);`

**Comment by iJamesPHP** [comment]
I have noticed some strange behaviour when using **onGenerateRoute** routes. I assumed that MaterialApp's _**builder**_ would've been wrapping these routes with LoadingProvider too but it doesn't seem to be so I am putting it in manually.

**Comment by sphamjoli** [comment]
Greetings this issue still seems to be a problem are there any updates on how to fix?

**Comment by ElAdrixHD** [comment]
> This error appears in flutter version 1.17.0, and fix by wrap LoadingProvider to MaterialApp builder `MaterialApp( builder: (context, widget) { return LoadingProvider( child: widget, ); }, );`

This answer works!
