### ISSUE TITLE
Loading overlay - dismissable at tap

### ISSUE THREAD

**Issue by IrvingArmenta-ML** [CaiJingLong/flutter_load_widget#2]
I noticed that the loading overlay can be dismissable at tap, which I don't think should be the default behavior, Users should not be able to dismiss the loading state (loading screen). 

Is there an option for it, like in `showDialog()` ? 

```
showDialog(
    context: context,
    barrierDismissible: false,
   // others args...
  );
```

**Comment by CaiJingLong** [comment]
OK, I will add a param to support it.

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_load_widget/blob/14910c88942a608e6226f05999db4f021f3e8893/example/lib/main.dart#L5-L14

Set `tapDismiss: false` can make every dialog can not click to disappear.

And, I will add a parameter to make each dialog can be set to close separately.

**Comment by CaiJingLong** [comment]
Update version to 0.1.4.
