### ISSUE TITLE
How to resolve the error ' method 'dismissAnim' was called on null'?

### ISSUE THREAD

**Issue by meditat** [CaiJingLong/flutter_load_widget#4]
E/flutter (13843): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The method 'dismissAnim' was called on null.
E/flutter (13843): Receiver: null
E/flutter (13843): Tried calling: dismissAnim()
E/flutter (13843): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
E/flutter (13843): #1      LoadingDismissFuture.dismiss (package:load/src/dismiss_future.dart:26:29)
E/flutter (13843): #2      FutureManager.dismissAll.<anonymous closure> (package:load/src/dismiss_future.dart:45:9)
E/flutter (13843): #3      List.forEach (dart:core-patch/growable_array.dart:278:8)
E/flutter (13843): #4      FutureManager.dismissAll (package:load/src/dismiss_future.dart:44:22)
E/flutter (13843): #5      _LoadingProviderState._realDismissDialog (package:load/src/provider.dart:122:33)
E/flutter (13843): #6      _LoadingProviderState.showLoading (package:load/src/provider.dart:71:5)
E/flutter (13843): #7      showLoadingDialog.<anonymous closure> (package:load/src/provider.dart:140:35)
E/flutter (13843): #8      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter (13843): #9      _rootRun (dart:async/zone.dart:1120:38)
E/flutter (13843): #10     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (13843): #11     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (13843): #12     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter (13843): #13     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (13843): #14     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (13843): #15     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter (13843): #16     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter (13843): #17     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter (13843): #18     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter (13843): #19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
E/flutter (13843): 
W/BiChannelGoogleApi(13843): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzak@7dd7cf1
E/JavaBinder(13843): *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
E/JavaBinder(13843): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/JavaBinder(13843): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/JavaBinder(13843): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/JavaBinder(13843): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/JavaBinder(13843): 	at com.google.firebase.auth.api.internal.zzcv.zzdx(Unknown Source:14)
E/JavaBinder(13843): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/JavaBinder(13843): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/JavaBinder(13843): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/JavaBinder(13843): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/JavaBinder(13843): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/JavaBinder(13843): 	at android.os.Binder.execTransact(Binder.java:731)
E/JavaBinder(13843): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/base.apk"],nativeLibraryDirectories=[/data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/lib/arm64, /data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/JavaBinder(13843): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/JavaBinder(13843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/JavaBinder(13843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/JavaBinder(13843): 	... 16 more
E/AndroidRuntime(13843): FATAL EXCEPTION: Binder:13843_4
E/AndroidRuntime(13843): Process: in.medit.volt_userapp, PID: 13843
E/AndroidRuntime(13843): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/util/ArrayMap;
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzam.zzc(Unknown Source:22)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzam.zzde(Unknown Source:17)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzam.zzdd(Unknown Source:8)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzan.zzdf(Unknown Source:1)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzm.isAnonymous(Unknown Source:47)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzat.zzi(Unknown Source:57)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.internal.zzat.zzg(Unknown Source:10)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.FirebaseAuth.zza(Unknown Source:62)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.FirebaseAuth$zzb.zza(Unknown Source:5)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.api.internal.zzcv.zzdx(Unknown Source:14)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.api.internal.zzen.zzen(Unknown Source:35)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.api.internal.zzen.zza(Unknown Source:41)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.api.internal.zzep.zza(Unknown Source:9)
E/AndroidRuntime(13843): 	at com.google.firebase.auth.api.internal.zzdx.dispatchTransaction(Unknown Source:9)
E/AndroidRuntime(13843): 	at com.google.android.gms.internal.firebase_auth.zza.onTransact(Unknown Source:13)
E/AndroidRuntime(13843): 	at android.os.Binder.execTransact(Binder.java:731)
E/AndroidRuntime(13843): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.util.ArrayMap" on path: DexPathList[[zip file "/data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/base.apk"],nativeLibraryDirectories=[/data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/lib/arm64, /data/app/in.medit.volt_userapp-FbtZAlDevc3wgpZoum27zg==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
E/AndroidRuntime(13843): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
E/AndroidRuntime(13843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(13843): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(13843): 	... 16 more

**Comment by CaiJingLong** [comment]
How to reproduce it?

Are you wrap the MaterialApp with `LoadingProvider`?

**Comment by meditat** [comment]
Yes, I got the issue, thanks

**Comment by ag12216** [comment]
Before showing Loading just check network is available or not then only show as it is called before the render
