### ISSUE TITLE
I found this error after I hide dialog too fast

### ISSUE THREAD

**Issue by Lykeosovandara** [CaiJingLong/flutter_load_widget#5]
Tried calling: showDismissAnim()
E/flutter (  705): #0      ProgressFuture.dismiss (package:flutter_progress_dialog/src/core/future.dart:25)
E/flutter (  705): #1      ProgressManager.dismissAll.<anonymous closure> (package:flutter_progress_dialog/src/core/manager.dart:17)
E/flutter (  705): #2      _GrowableList.forEach (dart:core-patch/growable_array.dart:283)
E/flutter (  705): #3      ProgressManager.dismissAll (package:flutter_progress_dialog/src/core/manager.dart:16)
E/flutter (  705): #4      dismissProgressDialog (package:flutter_progress_dialog/src/progress_dialog.dart:138)
E/flutter (  705): #5      Loading.hideLoading (package:barcode/src/utils/utils.dart:12)
E/flutter (  705): #6      LoginProvider.submit (package:barcode/src/providers/login_provider.dart:46)
E/flutter (  705): <asynchronous suspension>
E/flutter (  705): #7      Login.build.<anonymous closure> (package:barcode/src/screens/login.dart:59)
E/flutter (  705): <asynchronous suspension>
E/flutter (  705): #8      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654)
E/flutter (  705): #9      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729)
E/flutter (  705): #10     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
E/flutter (  705): #11     TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365)
E/flutter (  705): #12     TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275)
E/flutter (  705): #13     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455)
E/flutter (  705): #14     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75)
E/flutter (  705): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102)
E/flutter (  705): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218)
E/flutter (  705): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198)
E/flutter (  705): #18     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156)
E/flutter (  705): #19     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102)
E/flutter (  705): #20     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86)
E/flutter (  705): #21     _rootRunUnary (dart:async/zone.dart:1136)
E/flutter (  705): #22     _CustomZone.runUnary (dart:async/zone.dart:1029)
E/flutter (  705): #23     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
E/flutter (  705): #24     _invoke1 (dart:ui/hooks.dart:263)
E/flutter (  705): #25     _dispatchPointerDataPacket (dart:ui/hooks.dart:172)

**Comment by xapprika** [comment]
same here, i also have a problem hiding a dialog then showing an alert box

**Comment by xapprika** [comment]
I have made a workaround by putting the hide/dismiss function inside a Future.delayed with 1 second duration

**Comment by thanhhuan1990** [comment]
Same problem

**Comment by dsourav** [comment]
is there any solution to this problem

**Comment by bhargavsejpalindianic** [comment]
`void hideLoadingDialog() {
  print("hideLoadingDialog");
  Future.delayed(Duration.zero, () {
    if (_keys.isNotEmpty) {
      var key = _keys.first;
      //key?.currentState?.loadingKey?.currentState?.dismissAnim();
      key.currentState.dismissLoading();
    }
  });
}`

**Comment by p02diada** [comment]
same here
