### ISSUE TITLE
Flutter Inspector doesn't work after adding this package

### ISSUE THREAD

**Issue by zhanghuanchong** [CaiJingLong/flutter_load_widget#6]
Code structure:
![image](https://user-images.githubusercontent.com/3062319/67174738-d0f89580-f3f5-11e9-807b-1e1c6c984ae4.png)

Flutter version: 1.9.1
IDE: Android Studio

Once I enabled the "Select Widget Mode", the app will restart, which caused I cannot inspect the widgets on the previous page.

Can you help? Thanks in advance.

**Comment by p02diada** [comment]
Same error here, any news about it?

**Comment by CaiJingLong** [comment]
Try to use next code to include it:

```dart
 MaterialApp(
      builder: (context, widget) {
        return LoadingProvider(
          child: widget,
        );
      },
    );
```

**Comment by p02diada** [comment]
@CaiJingLong answer works. It should be the main example
